name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
  runs-on: ubuntu-latest
  steps:
    - run: echo "The job was automatically tiggered by a ${{ github.event_name }} event."
    - run: echo "This job is now runnning on a  ${{ runner.os }} server hosted by GitHub."
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check our repository code
      uses: actions/checkout@v2
    - run: echo "The repository ${{ github.repository }} has been cloned to the runner."
    - run: echo "The workflow is now ready to test your code on the runner."
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "Job status is ${{ job.status }}
    
    
